'%dev':
  db:
    show_sql: false
    name: corso
    server: localhost
    port: 3306
    username: root
    password: ''

'%prod':
  db:
    show_sql: false
    name: corso
    server: db
    port: 3306
    username: root
    password: ''

'%test':
  db:
    show_sql: false
    name: corso
    server: localhost
    port: 3306
    username: root
    password: ''

quarkus:
  datasource:
    db-kind: mysql
    username: ${db.username}
    password: ${db.password}
    jdbc:
      url: jdbc:mysql://${db.server}:${db.port}/${db.name}
  hibernate-orm:
    database:
      generation:
        ~: update